### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by tripokey** [xyrosource/blacklung#1]
Suggestion: Use toml with https://github.com/alexcrichton/toml-rs

**Comment by tripokey** [comment]
Investigate: https://github.com/mehcode/config-rs

**Comment by nthorne** [comment]
config-rs did looked like it was a bit nicer to use; gets my vote.

EDIT: config-rs seems to only be supporting reading from configuration files. Could be better to stick with toml-rs in case we need writing of options as well (such as modifying settings from console).

**Comment by tripokey** [comment]
Sounds good toml-rs seems to integrate nicely with https://serde.rs/ as well
