### ISSUE TITLE
consider linting

### ISSUE THREAD

**Issue by tripokey** [xyrosource/blacklung#13]
https://github.com/Manishearth/rust-clippy

**Comment by nthorne** [comment]
If we start using this one, which might be a good idea, since that might force at least me into writing more Rusty code, then we might as well start using the docopt! macro, which also depended on nightly.

**Comment by tripokey** [comment]
We can compile it separately and install it as a cargo subcommand without having blacklung depend on nightly or clippy.

**Comment by tripokey** [comment]
http://www.bashy.io/news/2016/03/05/clippy-linting-as-a-service/

**Comment by nthorne** [comment]
+1 looks really neat

**Comment by tripokey** [comment]
https://github.com/xyrosource/blacklung/pull/30
