### ISSUE TITLE
Use package version defined in cargo metadata in the application 

### ISSUE THREAD

**Issue by nthorne** [xyrosource/blacklung#27]
http://stackoverflow.com/questions/27840394/how-can-a-rust-program-access-metadata-from-its-cargo-package

Avoids duplication of version information. Also add a --version flag.

**Comment by nthorne** [comment]
.. Which only would work if the application is executed using cargo, which of course might not be the case.. Back to the drawing board.

**Comment by tripokey** [comment]
Maybe investigate if the build.rs script can be used to inject git describe into a generated file?

**Comment by nthorne** [comment]
Agree; sounds like a better idea, if possible.
